### ISSUE TITLE
Ark does not recognize zipped image archive.

### ISSUE THREAD

**Issue by avalonv** [elegantalchemist/literaryclock#2]
Hi, thanks for creating this project. I can't for the life of me get the PHP script to run, and my archive manager (KDE Ark) also does not recognize the zip files you included in the quote_to_image folder. Could you upload the images in another format somewhere else?

**Comment by elegantalchemist** [comment]
Hi

Sorry i'm not familiar with KDE Ark - apparently it struggles with multi-part zip archives. I am afraid I have no other way to upload - GitHub has size/number limits on files.

Try using p7zip instead of libzip as the library inside KDE Ark - this may allow multi part unzip. p7zip is the Linux form of 7-Zip.

https://www.reddit.com/r/kde/comments/ug8m15/ark_cant_extract_splitted_zip_file/

Or Is it possible to deal with the image unzip on a Windows system (they are just a standard multi-part Zip, created with 7-zip) - you can unzip and move the images over USB as a totally seperate step to the rest of the build.

**Comment by avalonv** [comment]
Would you accept a pull request with all the images in a single zip archive?
